name: destroy

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of the cluster/environment to destroy'
        required: true
        default: 'cnative'
      uninstall_apps:
        description: 'Uninstall the applications before destroying the cluster'
        type: choice
        options:
          - "true"
          - "false"
        required: true
        default: "true"
    push:
      branches:
        - 'main'
      tags:
        - '*.*.*'

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
      GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      CLUSTER_NAME: ${{ github.event.inputs.environment }}
      UNINSTALL_APPS: ${{ github.event.inputs.uninstall_apps }}
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: credentials
        run: "mkdir -p config && echo ${GOOGLE_CLOUD_CREDENTIALS} > config/google-cloud.json"
        shell: bash
      - name: run
        run: "docker run -v $(pwd)/config:/app/config --entrypoint /app/run_destroy.sh isi006/coder-development-cluster:latest ${GCLOUD_PROJECT} ${CLUSTER_NAME} ${UNINSTALL_APPS}"
        shell: bash
